### ISSUE TITLE
add students from LO calc/excel

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc-doc#1]
enhance adding students here: https://doc.cocalc.com/teaching-create-course.html#adding-students-to-the-course

* [ ] multiline box (fix screenshot)
* [ ] test+explain that copy/pasting from a column in libreoffice  calc or excel works, too (not just the comma-separated list)

**Comment by DrXyzzy** [comment]
Docs and screenshots updated. https://doc.cocalc.com/teaching-create-course.html#adding-students-to-the-course
