### ISSUE TITLE
Markdown help

### ISSUE THREAD

**Issue by kcrisman** [sagemathinc/cocalc-doc#11]
There is help in the docs for a lot of things, but (apparently) not for Markdown files. Could be useful to have a brief link for them.  

There are lots of places that mention Markdown used in other files, but only [this one](https://doc.cocalc.com/frame-editor.html#markdown) seems to mention it per se.)  Ideally such a brief link under "Features" would then have cross-links to other very useful features like [this one](https://doc.cocalc.com/howto/remarkjs-slideshow.html?highlight=markdown).

**Comment by kcrisman** [comment]
(Note this request is not for help within the Markdown file itself - see https://github.com/sagemathinc/cocalc/issues/4639 for that.)

**Comment by DrXyzzy** [comment]
I added a page that lists all the places you can use Markdown in CoCalc, with notes on special features and implementation. https://doc.cocalc.com/howto/markdown.html
