### ISSUE TITLE
Broken link to db-schema

### ISSUE THREAD

**Issue by BenGig** [sagemathinc/cocalc-doc#18]
On page

https://doc.cocalc.com/api/query.html

the link at the bottom of page is broken:

https://github.com/sagemathinc/cocalc/blob/master/src/smc-util/db-schema

**Comment by williamstein** [comment]
Thanks -- the correct link is https://github.com/sagemathinc/cocalc/tree/master/src/packages/util/db-schema

**Comment by DrXyzzy** [comment]
This information has been updated and is now at https://doc.cocalc.com/api/query.html#gettable-and-settable-fields
