### ISSUE TITLE
project settings → quotas

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc-doc#21]
the panel for usage and quotas changed. it's driven by the actual run quota configuration and the cgroup statistics. fields like member hosting is not shown for other deployments, but that's something we don't have to cover in these docs. in any case, example:

![Screenshot from 2022-03-18 09-19-47](https://user-images.githubusercontent.com/207405/158963341-bd26225e-3534-4572-8415-0641b83f2ca1.png)

each one is expandable and gives you more details, hopefully less confusion, not more. the memory quota and usage combines dedicated and limit. 

![Screenshot from 2022-03-18 09-22-51](https://user-images.githubusercontent.com/207405/158963704-bb877c14-6a71-4735-bae9-f9a27bc455d5.png)

---

in case you still have some of those phased out quota upgrades, a box to apply them shows up below. it briefly mentions your contribution, if there is any.

![Screenshot from 2022-03-18 09-26-27](https://user-images.githubusercontent.com/207405/158963993-9da64f8c-4673-4a55-906f-39fff26d4735.png)

at the bottom is the usual license dialog, no changes

**Comment by DrXyzzy** [comment]
Doc files and images updated for the new, and extremely useful, display & dialog.

https://doc.cocalc.com/project-settings.html#project-usage-and-quotas
