### ISSUE TITLE
the link to venv user guide is broken

### ISSUE THREAD

**Issue by aloukes** [sagemathinc/cocalc-doc#30]
should be https://virtualenv.pypa.io/en/20.0.25/user_guide.html
not
https://virtualenv.pypa.io/en/stable/userguide/

**Comment by DrXyzzy** [comment]
@aloukes thank you for pointing this out. Fixed in commit [e9eedc5](https://github.com/sagemathinc/cocalc-doc/commit/e9eedc50bd3fadd61ae448b50f2d225c6daf110c).
