### ISSUE TITLE
document per-project and per-account api keys

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc-doc#38]
Update text and screenshots

https://cocalc.com/settings section "API keys"

**Comment by DrXyzzy** [comment]
Done. See https://doc.cocalc.com/apikeys.html

**Comment by williamstein** [comment]
Could you add a link to https://github.com/sagemathinc/cocalc/discussions/6738 which has some more discussion of limits and might be a good place for people to ask followup questions...?

**Comment by DrXyzzy** [comment]
Done.
