### ISSUE TITLE
make the webserver example MUCH simpler

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc-doc#57]
The example here https://doc.cocalc.com/howto/webserver.html#example-code
of a python webserver is a bit complicated, involving creating a file and copy/pasting some weird old code (that's probably broken).  You an accomplish much the same using the webserver that is built into python:

```sh
python3 -m http.server
```

then visit

```
https://cocalc.com/[project_id]/server/8000/
```

Here's a screenshot: 

<img width="832" alt="image" src="https://github.com/sagemathinc/cocalc-doc/assets/1276278/55bc3e14-4e01-4182-852b-5acd919cc335">

**Comment by novoselt** [comment]
I think that running a web server is orthogonal to writing a web server, so I have deleted that example - the file listing is accessible via raw link. I have also replaced "not implemented" with compute servers! 1419725
