### ISSUE TITLE
jupyter kernel message: add "off" as a reason

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc-doc#59]
when you turn "off" a kernel like python, there is a yellow warning box (saying the kernel got a SIGKILL) and a link to https://doc.cocalc.com/howto/jupyter-kernel-terminated.html

on that page, nowhere is mentioned that this message happens due to such usage. it should just expand a bit in the beginning about capturing events of the underlying kernel process – and a regular "off" shutdown is one of them.

![Screenshot from 2024-06-04 08-45-39](https://github.com/sagemathinc/cocalc-doc/assets/207405/31d8eafa-8471-4698-ab6a-83296a28de9b)

**Comment by novoselt** [comment]
Done in 96f156e
